### ISSUE TITLE
Cannot reproduce the effect

### ISSUE THREAD

**Issue by EtoDemerzel0427** [esimov/ascii-fluid#1]
Hi Endre,

I tried to use your code, and had successfully opened the browser's webcam, seeing a bounding box around my face; and the terminal, with a lot of dots on it.——But they don't interact. I don't see the movement of my face reflects on the terminal. Meanwhile, the mouse click can render the fluid moving. I tried on my and my friend's Macbook Pro (both go 1.16.5), both don't work. Do you have any ideas?

By the way, with go modules, your Makefile should have a revision in line 13: from `COMMAND = osascript -e 'tell app "Terminal" to do script "go run $(PARENTDIR)/main.go"'` to `COMMAND = osascript -e 'tell app "Terminal" to do script "cd $(PARENTDIR) && go run main.go"'`

**Comment by esimov** [comment]
In MacOS you must set the accessibility authorization for the terminal you are running from.

Let me know if it does resolve your issue.

**Comment by EtoDemerzel0427** [comment]
> In MacOS you must set the accessibility authorization for the terminal you are running from.
> 
> Let me know if it does resolve your issue.

Would you mind giving some more detailed instructions?  I am not sure what kind of authorization I should give to the Terminal. Thanks.

**Comment by esimov** [comment]
This is what you need to do. 

![image](https://user-images.githubusercontent.com/883386/128286393-26bea35c-a6f4-4779-a524-7fcbcf0b6ea8.png)

**Comment by EtoDemerzel0427** [comment]
Thanks for your reply. I did as instructed, but the Terminal still does not interact with the webcam, and can only render the fluid with mouse clicks.

**Comment by esimov** [comment]
Right now I cannot help you more with this issue since I'm away, but will check it once I will get back home.

**Comment by esimov** [comment]
I have replaced completely a good portion of the code responsible of handling the data transferred trough the Websocket. Now the data received is handled between two terminal session with the help of a TCP connection instead of serving the face detection values encoded into a JSON file saved on the local system. I assume the reason why it does not worked for you was due to the fact that probably you couldn't access this file (it happened for me in certain circumstances).

I hope this will fix your issue. Let me know it works for you.

**Comment by EtoDemerzel0427** [comment]
Thanks for your help! Yes, it really is the Jsonfile's path that causes this problem. When enabling go modules, the default installation path of go get becomes `$GOPATH/pkg/mod/<package-name>`. After reading your newest reply I just changed the JsonFile path in the code and the problem went away. It would be better if the previous version could add an error handling step here, but I do think the update of using a TCP connection to exchange info is more elegant.
